swagger: "2.0"
info:
  version: "0.0.1"
  title: "Swagger jigsaw puzzle API"
basePath: /api/v1
schemes:
  - https
paths:
  /jigsaw:
    x-swagger-router-controller: puzzle.controller
    post:
      tags:
      - "puzzle"
      summary: "Add a new puzzle to find a solution"
      description: "Will take as input a jigsaw puzzle and must respond with a solution, or say that no solution exists."
      consumes:
      - "application/json"
      produces:
      - "application/json"
      operationId: getSolutionPuzzle
      parameters:
        - name: puzzle
          in: body
          description: "The jigsaw puzzle to find a solution"
          required: true
          schema:
            $ref: "#/definitions/Puzzle"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/SolutionResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  Piece:
    type: array
    items:
      type: string
  Puzzle:
    type: object
    properties:
      boardSize:
        type: number
      pieces:
        type: array
        items:
          $ref: '#/definitions/Piece'
  SolutionResponse:
    type: object
    properties:
      solution:
        type: 
          - array
          - 'null'
        items:
          type: string
  ErrorResponse:
    required:
      - code
      - message
    properties:
      code:
        type: number
      message:
        type: string
      description:
        type: string
